name: Build EXE and Release

on:
  push:
    tags:
      - 'v*.*.*'

jobs:
  build-windows:
    runs-on: windows-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: pip install pyinstaller

      - name: Build EXE
        run: pyinstaller --onefile hello.py

      - name: Upload EXE to Release
        uses: softprops/action-gh-release@v2
        with:
          files: dist/hello.exe
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
